// This file is generated from Rust API response/request types.
// Run `cargo test --manifest-path api/Cargo.toml export_api_types -- --ignored` to update it.
// Do not edit this file by hand.

export type Visibility = "Public" | "Private";

export type RepoRole = "Reader" | "Writer" | "Maintainer" | "Owner";

export type RepoPublicationState = "PendingFirstPush" | "PendingPublish" | "Published";

export type FirstPushTokenStatus = "Active" | "Expired" | "Used";

export type StagedFileChangeKind = "Added" | "Modified" | "Deleted";

export type ProjectionPreviewAudience = "owner" | "public";

export type ProjectionPreviewSource = "live" | "review";

export type AccountSessionResponse = { identity: SessionIdentity | null, user: UserResponse | null, };

export type UserResponse = { id: string, handle: string, email: string, email_verified: boolean, };

export type SessionResponse = { identity: SessionIdentity | null, repo: SessionRepo, principal_id: string, capabilities: SessionCapabilities, };

export type SessionIdentity = { pairwise_sub: string, email: string | null, email_verified: boolean, };

export type SessionRepo = { id: string, publication_state: RepoPublicationState, role: RepoRole | null, };

export type SessionCapabilities = { read: boolean, write: boolean, };

export type RepoSummaryResponse = { id: string, owner_handle: string, name: string, lifecycle_state: RepoPublicationState, default_visibility: Visibility, role: RepoRole | null, staged_update_pending: boolean, };

export type CreateRepoRequest = { name: string, visibility: Visibility | null, };

export type CreateRepoResponse = { repo: RepoSummaryResponse, setup: RepoSetupResponse, };

export type DeleteRepoResponse = { id: string, deleted: boolean, };

export type RepoSetupResponse = { repo: RepoSummaryResponse, git_remote_path: string, remote_name: string, push_branch: string, push_enabled: boolean, token: FirstPushTokenResponse | null, push_token: GitPushTokenResponse | null, };

export type RepoGitCredentialResponse = { git_remote_path: string, remote_name: string, push_token: GitPushTokenResponse, };

export type FirstPushTokenResponse = { status: FirstPushTokenStatus, created_at_unix: number, expires_at_unix: number, used_at_unix: number | null, secret: string | null, };

export type GitPushTokenResponse = { created_at_unix: number, secret: string | null, };

export type RepoFileResponse = { path: string, oid: string, tracked: boolean, visibility: Visibility, };

export type RepoSettingsResponse = { default_new_file_visibility: Visibility, review_pushes_before_applying: boolean, };

export type UpdateRepoSettingsRequest = { default_new_file_visibility: Visibility, review_pushes_before_applying: boolean, };

export type UpdateFileVisibilityRequest = { paths: Array<string>, visibility: Visibility, };

export type UpdateStagedFileVisibilityRequest = { paths: Array<string>, visibility: Visibility, };

export type PendingImportReviewResponse = { publication_state: RepoPublicationState, default_visibility: Visibility, files: Array<RepoFileResponse>, };

export type StagedUpdateResponse = { id: string, branch: string, base_live_commit_id: string | null, message: string, files: Array<StagedFileResponse>, };

export type StagedFileResponse = { path: string, kind: StagedFileChangeKind, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type ProjectionPreviewRequest = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource | null, };

export type ProjectionPreviewResponse = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource, repo_id: string, principal_id: string, head_oid: string | null, files: Array<ProjectionPreviewFileResponse>, commits: Array<ProjectionPreviewCommitResponse>, summary: ProjectionPreviewSummaryResponse, };

export type ProjectionPreviewFileResponse = { path: string, oid: string, visibility: Visibility, };

export type ProjectionPreviewCommitResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, synthetic: boolean, change_count: number, };

export type ProjectionPreviewSummaryResponse = { visible_files: number, hidden_files: number, visible_commits: number, hidden_commits: number, synthetic_commits: number, };
