// This file is generated from Rust API response/request types.
// Run `cargo run --manifest-path api/Cargo.toml --features type-export --bin export-api-types` to update it.
// Do not edit this file by hand.

export type Visibility = "Public" | "Private";

export type RepositoryActor = "Public" | "Member" | "Owner";

export type RepositoryMemberPermissions = { can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, };

export type RepositoryInviteState = "Pending" | "Accepted" | "Revoked" | "Expired";

export type RepoPublicationState = "Unpublished" | "Published";

export type RepoChangeEvent = { repo_id: string, version: number, kind: RepoChangeKind, };

export type FirstPushTokenStatus = "Active" | "Expired" | "Used";

export type FileChangeKind = "Added" | "Modified" | "Deleted";

export type ConfigVisibility = "public" | "private";

export type RepoConfig = { $schema?: string | null, kind: string, version: number, visibility: RepoConfigVisibility, history: RepoConfigHistory, };

export type RepoConfigVisibility = { default: ConfigVisibility, rules: Array<RepoConfigVisibilityRule>, };

export type RepoConfigVisibilityRule = { path: string, visibility: ConfigVisibility, };

export type RepoConfigHistory = { rewrites: Array<HistoryRewriteRequest>, };

export type HistoryRewriteRequest = { path: string, action: HistoryRewriteAction, };

export type HistoryRewriteAction = "redact-public-history";

export type RequestActorRole = "Public" | "Member" | "Owner";

export type RequestAudience = "Public" | "Private";

export type RequestState = "Working" | "ReadyForReview" | "Completed";

export type RequestAssessmentOutcome = "Accepted" | "Neutral" | "Rejected";

export type RequestReviewExitReason = "AuthorReturned" | "ChangesRequested" | "RevisionPushed" | "ContentEdited";

export type GitOid = string;

export type RequestEventKind = "Started" | "ReadyForReview" | "ReturnedToWorking" | "RevisionPushed" | "Held" | "HoldReleased" | "Assessed" | "Merged" | "Closed" | "Settled" | "IdentityEdited" | "DiscussionResolved" | "DiscussionReopened";

export type ProjectionPreviewAudience = "private" | "public";

export type ProjectionPreviewSource = "live";

export type AccountSessionResponse = { identity: SessionIdentity | null, user: UserResponse | null, credit_balance_credits: number | null, };

export type UserResponse = { id: string, handle: string, email: string, email_verified: boolean, };

export type SessionResponse = { identity: SessionIdentity | null, repo: SessionRepo, principal_id: string, capabilities: SessionCapabilities, };

export type SessionIdentity = { user_id: string, email: string | null, email_verified: boolean, };

export type SessionRepo = { id: string, publication_state: RepoPublicationState, access: RepositoryAccessResponse, };

export type SessionCapabilities = { read: boolean, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type DeviceLoginStatus = "Pending" | "Complete";

export type DeviceLoginStartResponse = { device_code: string, user_code: string, verification_url: string, expires_at_unix: number, poll_interval_secs: number, };

export type DeviceLoginPollResponse = { status: DeviceLoginStatus, session_token: string | null, expires_at_unix: number, identity: SessionIdentity | null, };

export type DeviceLoginCompleteResponse = { status: DeviceLoginStatus, };

export type BrowserLoginStartRequest = { callback_url: string, };

export type BrowserLoginStartResponse = { request_id: string, request_secret: string, authorization_url: string, expires_at_unix: number, };

export type BrowserLoginCompleteResponse = { callback_url: string, };

export type BrowserLoginExchangeRequest = { request_secret: string, callback_code: string, };

export type CliSessionTokenResponse = { session_token: string, expires_at_unix: number, identity: SessionIdentity, };

export type CliExchangeGrantResponse = { exchange_token: string, expires_at_unix: number, };

export type CliExchangeGrantExchangeRequest = { exchange_token: string, };

export type CliSessionsResponse = { sessions: Array<CliSessionResponse>, };

export type CliSessionResponse = { id: string, label: string, created_at_unix: number, last_used_at_unix: number | null, expires_at_unix: number, };

export type RepoSummaryResponse = { id: string, owner_handle: string, name: string, lifecycle_state: RepoPublicationState, default_visibility: Visibility, change_version: number, access: RepositoryAccessResponse, ready_for_review_count: number, request_permissions: RepoRequestPermissionsResponse, };

export type RepoRequestPermissionsResponse = { can_start_request: boolean, uses_credit_stake: boolean, };

export type CreateRepoRequest = { name: string, visibility: Visibility | null, };

export type CreateRepoResponse = { repo: RepoSummaryResponse, init: RepoInitResponse, };

export type DeleteRepoResponse = { id: string, deleted: boolean, };

export type CreatePushIntentRequest = { head_oid: string, base_config_hash: string, config: RepoConfig, };

export type CreatePushIntentResponse = { token: string, base_head_oid: GitOid | null, expires_at_unix: number, };

export type RepoInitResponse = { repo: RepoSummaryResponse, git_remote_url: string, remote_name: string, push_branch: string, token: FirstPushTokenResponse | null, push_token: GitPushTokenResponse | null, };

export type RepoConfigResponse = { config: RepoConfig, config_hash: string, lifecycle_state: RepoPublicationState, access: RepositoryAccessResponse, head_oid: string | null, };

export type FirstPushTokenResponse = { status: FirstPushTokenStatus, created_at_unix: number, expires_at_unix: number, used_at_unix: number | null, secret: string | null, };

export type GitPushTokenResponse = { created_at_unix: number, secret: string | null, };

export type RepoFileResponse = { path: string, oid: string, tracked: boolean, visibility: Visibility, };

export type RepoFileContentRequest = { path: string, };

export type RepoFileContentResponse = { path: string, oid: string, visibility: Visibility, size_bytes: number, content: ReviewFileContentResponse, };

export type RepositoryAccessResponse = { actor: RepositoryActor, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type RepositoryCollaborationResponse = { members: Array<RepositoryMemberResponse>, invites: Array<RepositoryInviteResponse>, };

export type RepositoryMemberResponse = { user_id: string, handle: string, email: string, permissions: RepositoryMemberPermissions, created_at_unix: number, updated_at_unix: number, };

export type RepositoryInviteResponse = { id: string, invited_email: string, permissions: RepositoryMemberPermissions, state: RepositoryInviteState, expires_at_unix: number, };

export type CreateRepositoryInviteRequest = { email: string, permissions: RepositoryMemberPermissions, };

export type CreateRepositoryInviteResponse = { invite: RepositoryInviteResponse, invite_url: string, };

export type UpdateRepositoryMemberRequest = { permissions: RepositoryMemberPermissions, };

export type RepositoryInviteLookupResponse = { repo_id: string, owner_handle: string, repo_name: string, invited_email: string, permissions: RepositoryMemberPermissions, expires_at_unix: number, };

export type AcceptRepositoryInviteResponse = { repo: RepoSummaryResponse, member: RepositoryMemberResponse, };

export type CommitHistoryRequest = { audience: ProjectionPreviewAudience | null, };

export type CommitFileDiffRequest = { audience: ProjectionPreviewAudience | null, path: string, };

export type RequestFileDiffRequest = { path: string, };

export type RequestChangeBlockFilesResponse = { change_block: RequestChangeBlockResponse, files: Array<CommitFileResponse>, };

export type ReviewFileContentResponse = { "kind": "text", text: string, } | { "kind": "binary", oid: string, size_bytes: number, };

export type ReviewFileDiffResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_content: ReviewFileContentResponse | null, new_content: ReviewFileContentResponse | null, };

export type CommitHistoryResponse = { audience: ProjectionPreviewAudience, repo_id: string, view_key: string, generation: string, commits: Array<CommitSummaryResponse>, };

export type CommitSummaryResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, change_count: number, };

export type CommitDetailResponse = { audience: ProjectionPreviewAudience, repo_id: string, view_key: string, projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, change_count: number, files: Array<CommitFileResponse>, };

export type CommitFileResponse = { path: string, kind: FileChangeKind, old_mode: string | null, new_mode: string | null, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type ProjectionPreviewRequest = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource | null, };

export type ProjectionPreviewResponse = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource, repo_id: string, view_key: string, head_oid: string | null, files: Array<ProjectionPreviewFileResponse>, commits: Array<ProjectionPreviewCommitResponse>, summary: ProjectionPreviewSummaryResponse, };

export type ProjectionPreviewFileResponse = { path: string, oid: string, visibility: Visibility, };

export type ProjectionPreviewCommitResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, visibility: ProjectionPreviewCommitVisibilityResponse, change_count: number, };

export type ProjectionPreviewCommitVisibilityResponse = "FullyPublic" | "Mixed" | "FullyPrivate";

export type ProjectionPreviewSummaryResponse = { visible_files: number, hidden_files: number, visible_commits: number, hidden_commits: number, };

export type RequestQueueSection = "your_work" | "ready" | "completed";

export type RequestListResponse = { requests: Array<RequestListItemResponse>, next_cursor: string | null, };

export type RequestDetailResponse = { request: RequestSummaryResponse, };

export type RequestMutationResponse = { request: RequestSummaryResponse, };

export type RequestListItemResponse = { id: string, name: string, title: string, author_role: RequestActorRole, audience: RequestAudience, head_oid: GitOid, state: RequestState, current_stake_credits: number, assessment_outcome: RequestAssessmentOutcome | null, ready_at_unix: number | null, held_at_unix: number | null, updated_at_unix: number, mergeability: RequestMergeabilityResponse, };

export type RequestSummaryResponse = { id: string, name: string, title: string, description_markdown: string, author_user_id: string, author_role: RequestActorRole, audience: RequestAudience, base_main_oid: GitOid, head_oid: GitOid, state: RequestState, activity_version: number, current_stake_credits: number, first_ready_at_unix: number | null, ready_at_unix: number | null, held_at_unix: number | null, held_by_user_id: string | null, assessment_outcome: RequestAssessmentOutcome | null, assessment_body_markdown: string | null, assessed_at_unix: number | null, assessed_by_user_id: string | null, completed_at_unix: number | null, completed_by_user_id: string | null, merged_at_unix: number | null, merged_by_user_id: string | null, merged_head_oid: GitOid | null, merged_main_oid: GitOid | null, created_at_unix: number, updated_at_unix: number, invitees: Array<RequestInviteeResponse>, assessment_previews: Array<RequestSettlementPreviewResponse>, permissions: RequestPermissionsResponse, mergeability: RequestMergeabilityResponse, };

export type RequestSettlementPreviewResponse = { outcome: RequestAssessmentOutcome, stake_credits: number, refunded_credits: number, reward_credits: number, burned_credits: number, };

export type RequestInviteeResponse = { user: RequestActorSummaryResponse, invited_by_user_id: string, created_at_unix: number, };

export type AddRequestInviteeRequest = { handle: string, };

export type RemoveRequestInviteeRequest = { handle: string, };

export type RequestInviteeMutationResponse = { request: RequestSummaryResponse, invitee: RequestInviteeResponse, };

export type LeaveRequestResponse = { invitee: RequestInviteeResponse, };

export type RequestPermissionsResponse = { can_view_activity: boolean, can_open_discussion: boolean, can_reply_to_discussion: boolean, can_edit_identity: boolean, can_pull_branch: boolean, can_push_branch: boolean, can_mark_ready: boolean, can_return_to_working: boolean, can_manage_invitees: boolean, can_leave_request: boolean, can_hold: boolean, can_request_changes: boolean, can_assess: boolean, can_close: boolean, can_merge: boolean, };

export type RequestMergeabilityStatus = "Ready" | "Completed" | "Working" | "NotMaintainer" | "MissingRequestBranch";

export type RequestMergeabilityResponse = { status: RequestMergeabilityStatus, current_main_oid: GitOid | null, request_head_oid: GitOid, reason: string | null, };

export type RequestEventResponse = { id: string, position: number, actor: RequestActorSummaryResponse, kind: RequestEventKind, payload: RequestEventPayload, created_at_unix: number, };

export type RequestEventPayload = { "Started": { title: string, description_markdown: string, } } | { "ReadyForReview": { head_oid: string, stake_credits: number, } } | { "ReturnedToWorking": { head_oid: string, stake_credits: number, reason: RequestReviewExitReason, } } | { "RevisionPushed": { old_head_oid: string, new_head_oid: string, note: string | null, } } | { "Held": { head_oid: string, } } | { "HoldReleased": { head_oid: string, } } | { "Assessed": { head_oid: string, outcome: RequestAssessmentOutcome, body_markdown: string | null, stake_credits: number, } } | { "Merged": { head_oid: string, main_oid: string, } } | { "Closed": { head_oid: string, } } | { "Settled": { settlement: RequestSettlement, } } | { "IdentityEdited": { before: RequestIdentityAuditFact, after: RequestIdentityAuditFact, } } | { "DiscussionResolved": { discussion_id: string, } } | { "DiscussionReopened": { discussion_id: string, } };

export type RequestIdentityAuditFact = { title_sha256: string, title_byte_count: number, description_sha256: string, description_byte_count: number, };

export type RequestSettlement = { outcome: RequestAssessmentOutcome, stake_credits: number, refunded_credits: number, reward_credits: number, burned_credits: number, settled_at_unix: number, };

export type RequestActorSummaryResponse = { id: string, handle: string, };

export type RequestDiscussionStatus = "Dormant" | "Open" | "Resolved";

export type RequestDiscussionReplyResponse = { id: string, discussion_id: string, position: number, author: RequestActorSummaryResponse, body_markdown: string, reply_to_reply_id: string | null, child_reply_count: number, can_reply: boolean, created_at_unix: number, };

export type RequestDiscussionSummaryResponse = { id: string, request_id: string, client_discussion_id: string, opened_position: number, last_activity_position: number, author: RequestActorSummaryResponse, body_markdown: string | null, change_block: RequestChangeBlockResponse | null, status: RequestDiscussionStatus, reply_count: number, unread_count: number, latest_replies: Array<RequestDiscussionReplyResponse>, created_at_unix: number, resolved_at_unix: number | null, resolved_by: RequestActorSummaryResponse | null, };

export type RequestChangeBlockResponse = { id: string, position: number, old_head_oid: string, new_head_oid: string, created_at_unix: number, };

export type RequestDiscussionPageResponse = { discussions: Array<RequestDiscussionSummaryResponse>, next_cursor: string | null, snapshot_version: number, };

export type RequestDiscussionRepliesPageResponse = { replies: Array<RequestDiscussionReplyResponse>, next_before_position: number | null, };

export type RequestDiscussionMutationResponse = { discussion: RequestDiscussionSummaryResponse, };

export type RequestDiscussionReplyMutationResponse = { discussion: RequestDiscussionSummaryResponse, reply: RequestDiscussionReplyResponse, };

export type RequestDiscussionChangesResponse = { discussions: Array<RequestDiscussionSummaryResponse>, through_position: number, has_more: boolean, };

export type RequestDiscussionReadResponse = { read_through_position: number, };

export type RequestActivityPageResponse = { events: Array<RequestEventResponse>, through_position: number, };

export type RequestCloseResponse = { deleted: boolean, request: RequestSummaryResponse | null, };

export type StartRequestRequest = { name: string, title: string | null, audience: RequestAudience, };

export type ReadyRequestRequest = { stake_credits: number | null, };

export type AssessRequestRequest = { outcome: RequestAssessmentOutcome, body_markdown: string | null, };

export type EditRequestIdentityRequest = { title: string | null, description_markdown: string | null, };

export type CreateRequestDiscussionRequest = { body_markdown: string, client_discussion_id: string, };

export type CreateRequestDiscussionReplyRequest = { body_markdown: string, client_reply_id: string, reply_to_reply_id: string | null, };

export type ReopenAndReplyRequest = { body_markdown: string, client_reply_id: string, reply_to_reply_id: string | null, };

export type MarkRequestDiscussionReadRequest = { through_position: number, };

export type RepoChangeKind = "Connected" | "Lagged" | { "RepositoryChanged": { reason: string, } } | { "RequestTimelineChanged": { request_id: string, discussion_id: string, through_position: number, audience: RequestAudience, } };

export const ApiRouteTemplates = {
  accountSession: "/v1/session",
  cliDeviceLoginComplete: "/v1/cli/device-login/{user_code}/complete",
  cliBrowserLoginComplete: "/v1/cli/browser-login/{request_id}/complete",
  cliExchangeGrants: "/v1/cli/exchange-grants",
  cliSessions: "/v1/cli/sessions",
  cliSessionById: "/v1/cli/sessions/{session_id}",
  repos: "/v1/repos",
  repo: "/v1/repos/{owner}/{repo}",
  repoConfig: "/v1/repos/{owner}/{repo}/config",
  repoPushIntents: "/v1/repos/{owner}/{repo}/push-intents",
  repoRequests: "/v1/repos/{owner}/{repo}/requests",
  repoRequestQueue: "/v1/repos/{owner}/{repo}/requests/queue",
  repoRequest: "/v1/repos/{owner}/{repo}/requests/{request_id}",
  repoRequestReady: "/v1/repos/{owner}/{repo}/requests/{request_id}/ready",
  repoRequestWorking: "/v1/repos/{owner}/{repo}/requests/{request_id}/working",
  repoRequestHold: "/v1/repos/{owner}/{repo}/requests/{request_id}/hold",
  repoRequestRequestChanges: "/v1/repos/{owner}/{repo}/requests/{request_id}/request-changes",
  repoRequestAssessment: "/v1/repos/{owner}/{repo}/requests/{request_id}/assessment",
  repoRequestMerge: "/v1/repos/{owner}/{repo}/requests/{request_id}/merge",
  repoRequestInvitees: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees",
  repoRequestInviteesMe: "/v1/repos/{owner}/{repo}/requests/{request_id}/invitees/me",
  repoSession: "/v1/repos/{owner}/{repo}/session",
  repoFiles: "/v1/repos/{owner}/{repo}/files",
  repoFileContent: "/v1/repos/{owner}/{repo}/files/content",
  repoRequestChangeBlockFiles: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes/{block_id}",
  repoRequestChangeBlockFileDiff: "/v1/repos/{owner}/{repo}/requests/{request_id}/changes/{block_id}/file-diff",
  repoRequestDiscussions: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline",
  repoRequestDiscussionChanges: "/v1/repos/{owner}/{repo}/requests/{request_id}/timeline/changes",
  repoRequestDiscussionReplies: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/replies",
  repoRequestDiscussionResolve: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/resolve",
  repoRequestDiscussionReopen: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen",
  repoRequestDiscussionReopenAndReply: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/reopen-and-reply",
  repoRequestDiscussionRead: "/v1/repos/{owner}/{repo}/requests/{request_id}/threads/{discussion_id}/read",
  repoRequestActivity: "/v1/repos/{owner}/{repo}/requests/{request_id}/activity",
  repoEvents: "/v1/repos/{owner}/{repo}/events",
  repoCommits: "/v1/repos/{owner}/{repo}/commits",
  repoCommit: "/v1/repos/{owner}/{repo}/commits/{commit_id}",
  repoCommitFileDiff: "/v1/repos/{owner}/{repo}/commits/{commit_id}/file-diff",
  repoMembers: "/v1/repos/{owner}/{repo}/members",
  repoInvites: "/v1/repos/{owner}/{repo}/invites",
  repoInvite: "/v1/repos/{owner}/{repo}/invites/{invite_id}",
  repoMember: "/v1/repos/{owner}/{repo}/members/{member_user_id}",
  repositoryInvite: "/v1/repository-invites/{token}",
  repositoryInviteAccept: "/v1/repository-invites/{token}/accept",
  repoProjectionPreview: "/v1/repos/{owner}/{repo}/projection-preview",
  gitRepo: "/git/{mode}/{org}/{repo}",
} as const;

export function buildApiPath(
  template: string,
  params: Readonly<Record<string, string>> = {},
): string {
  return template.replace(/\{([^}]+)\}/g, (_match, key: string) => {
    const value = params[key]
    if (value === undefined) throw new Error(`Missing API route parameter: ${key}`)
    return encodeURIComponent(value)
  })
}
