// This file is generated from Rust API response/request types.
// Run `cargo test --manifest-path api/Cargo.toml export_api_types -- --ignored` to update it.
// Do not edit this file by hand.

export type Visibility = "Public" | "Private";

export type RepositoryActor = "Public" | "Member" | "Owner";

export type RepositoryMemberPermissions = { can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, };

export type RepositoryInviteState = "Pending" | "Accepted" | "Revoked" | "Expired";

export type RepoPublicationState = "Unpublished" | "Published";

export type FirstPushTokenStatus = "Active" | "Expired" | "Used";

export type StagedFileChangeKind = "Added" | "Modified" | "Deleted";

export type ProjectionPreviewAudience = "owner" | "public";

export type ProjectionPreviewSource = "live" | "review";

export type AccountSessionResponse = { identity: SessionIdentity | null, user: UserResponse | null, };

export type UserResponse = { id: string, handle: string, email: string, email_verified: boolean, };

export type SessionResponse = { identity: SessionIdentity | null, repo: SessionRepo, principal_id: string, capabilities: SessionCapabilities, };

export type SessionIdentity = { user_id: string, email: string | null, email_verified: boolean, };

export type SessionRepo = { id: string, publication_state: RepoPublicationState, access: RepositoryAccessResponse, };

export type SessionCapabilities = { read: boolean, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_update_repo_settings: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type DeviceLoginStatus = "Pending" | "Complete";

export type DeviceLoginStartResponse = { device_code: string, user_code: string, verification_url: string, expires_at_unix: number, poll_interval_secs: number, };

export type DeviceLoginPollResponse = { status: DeviceLoginStatus, session_token: string | null, expires_at_unix: number, identity: SessionIdentity | null, };

export type DeviceLoginCompleteResponse = { status: DeviceLoginStatus, };

export type BrowserLoginStartRequest = { callback_url: string, };

export type BrowserLoginStartResponse = { request_id: string, request_secret: string, authorization_url: string, expires_at_unix: number, };

export type BrowserLoginCompleteResponse = { callback_url: string, };

export type BrowserLoginExchangeRequest = { request_secret: string, callback_code: string, };

export type CliSessionTokenResponse = { session_token: string, expires_at_unix: number, identity: SessionIdentity, };

export type CliExchangeGrantResponse = { exchange_token: string, expires_at_unix: number, };

export type CliExchangeGrantExchangeRequest = { exchange_token: string, };

export type CliSessionsResponse = { sessions: Array<CliSessionResponse>, };

export type CliSessionResponse = { id: string, label: string, created_at_unix: number, last_used_at_unix: number | null, expires_at_unix: number, };

export type RepoSummaryResponse = { id: string, owner_handle: string, name: string, lifecycle_state: RepoPublicationState, default_visibility: Visibility, change_version: number, access: RepositoryAccessResponse, pending_import_pending: boolean, staged_update_pending: boolean, push_blocked_by_staged_update: boolean, };

export type CreateRepoRequest = { name: string, visibility: Visibility | null, };

export type CreateRepoResponse = { repo: RepoSummaryResponse, init: RepoInitResponse, };

export type DeleteRepoResponse = { id: string, deleted: boolean, };

export type RepoInitResponse = { repo: RepoSummaryResponse, git_remote_url: string, remote_name: string, push_branch: string, token: FirstPushTokenResponse | null, push_token: GitPushTokenResponse | null, review_url: string, };

export type RepoCloneCredentialResponse = { git_remote_path: string, token: GitCloneTokenResponse, };

export type FirstPushTokenResponse = { status: FirstPushTokenStatus, created_at_unix: number, expires_at_unix: number, used_at_unix: number | null, secret: string | null, };

export type GitPushTokenResponse = { created_at_unix: number, secret: string | null, };

export type GitCloneTokenResponse = { created_at_unix: number, secret: string | null, };

export type RepoFileResponse = { path: string, oid: string, tracked: boolean, visibility: Visibility, };

export type RepoSettingsResponse = { default_new_file_visibility: Visibility, review_pushes_before_applying: boolean, };

export type UpdateRepoSettingsRequest = { default_new_file_visibility: Visibility, review_pushes_before_applying: boolean, };

export type RepositoryAccessResponse = { actor: RepositoryActor, can_read_private_files: boolean, can_push: boolean, can_change_file_visibility: boolean, can_apply_changes: boolean, can_update_repo_settings: boolean, can_manage_members: boolean, can_delete_repo: boolean, };

export type RepositoryCollaborationResponse = { members: Array<RepositoryMemberResponse>, invites: Array<RepositoryInviteResponse>, };

export type RepositoryMemberResponse = { user_id: string, handle: string, email: string, permissions: RepositoryMemberPermissions, created_at_unix: number, updated_at_unix: number, };

export type RepositoryInviteResponse = { id: string, invited_email: string, permissions: RepositoryMemberPermissions, state: RepositoryInviteState, expires_at_unix: number, };

export type CreateRepositoryInviteRequest = { email: string, permissions: RepositoryMemberPermissions, };

export type CreateRepositoryInviteResponse = { invite: RepositoryInviteResponse, invite_url: string, };

export type UpdateRepositoryMemberRequest = { permissions: RepositoryMemberPermissions, };

export type RepositoryInviteLookupResponse = { repo_id: string, owner_handle: string, repo_name: string, invited_email: string, permissions: RepositoryMemberPermissions, expires_at_unix: number, };

export type AcceptRepositoryInviteResponse = { repo: RepoSummaryResponse, member: RepositoryMemberResponse, };

export type UpdateFileVisibilityRequest = { paths: Array<string>, visibility: Visibility, };

export type UpdateStagedFileVisibilityRequest = { paths: Array<string>, visibility: Visibility, };

export type ReviewFileDiffRequest = { path: string, };

export type CommitHistoryRequest = { audience: ProjectionPreviewAudience | null, };

export type CommitFileDiffRequest = { audience: ProjectionPreviewAudience | null, path: string, };

export type ReviewFileContentResponse = { "kind": "text", text: string, } | { "kind": "binary", oid: string, size_bytes: number, };

export type ReviewFileDiffResponse = { path: string, kind: StagedFileChangeKind, old_content: ReviewFileContentResponse | null, new_content: ReviewFileContentResponse | null, };

export type ReviewLineDiffResponse = { additions: number, deletions: number, };

export type PendingImportReviewResponse = { publication_state: RepoPublicationState, default_visibility: Visibility, line_diff: ReviewLineDiffResponse | null, files: Array<RepoFileResponse>, };

export type StagedUpdateResponse = { id: string, branch: string, base_live_commit_id: string | null, message: string, line_diff: ReviewLineDiffResponse | null, files: Array<StagedFileResponse>, };

export type StagedFileResponse = { path: string, kind: StagedFileChangeKind, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type CommitHistoryResponse = { audience: ProjectionPreviewAudience, repo_id: string, principal_id: string, commits: Array<CommitSummaryResponse>, };

export type CommitSummaryResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, change_count: number, };

export type CommitDetailResponse = { audience: ProjectionPreviewAudience, repo_id: string, principal_id: string, projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, change_count: number, files: Array<CommitFileResponse>, };

export type CommitFileResponse = { path: string, kind: StagedFileChangeKind, old_oid: string | null, new_oid: string | null, visibility: Visibility, };

export type ProjectionPreviewRequest = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource | null, };

export type ProjectionPreviewResponse = { audience: ProjectionPreviewAudience, source: ProjectionPreviewSource, repo_id: string, principal_id: string, head_oid: string | null, files: Array<ProjectionPreviewFileResponse>, commits: Array<ProjectionPreviewCommitResponse>, summary: ProjectionPreviewSummaryResponse, };

export type ProjectionPreviewFileResponse = { path: string, oid: string, visibility: Visibility, };

export type ProjectionPreviewCommitResponse = { projected_id: string, logical_commit_id: string, parent_projected_id: string | null, author: string | null, message: string, visibility: ProjectionPreviewCommitVisibilityResponse, change_count: number, };

export type ProjectionPreviewCommitVisibilityResponse = "FullyPublic" | "Mixed" | "FullyPrivate";

export type ProjectionPreviewSummaryResponse = { visible_files: number, hidden_files: number, visible_commits: number, hidden_commits: number, };

export const CliAuthApiEndpoints = {
  accountSession: "/v1/session",
  cliSession: "/v1/cli/session",
  deviceLoginStart: "/v1/cli/device-login",
  deviceLoginPoll: "/v1/cli/device-login/{device_code}/poll",
  browserLoginStart: "/v1/cli/browser-login",
  browserLoginExchange: "/v1/cli/browser-login/{request_id}/exchange",
  exchangeGrantExchange: "/v1/cli/exchange-grants/exchange",
} as const;
