use super::metadata_schema::*;
use sea_orm::DbErr;
use sea_orm_migration::{manager::SchemaManager, prelude::*};

pub async fn ensure_metadata_lock_and_cleanup_tables(
    manager: &SchemaManager<'_>,
) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(MetadataLocks::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(MetadataLocks::Key)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(RepoStorageCleanupJobs::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::RepoId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::Generation)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::OwnerHandle)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::RepoName)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::Attempts)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::NextRunAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(RepoStorageCleanupJobs::LastError).text())
                .col(ColumnDef::new(RepoStorageCleanupJobs::CompletedAtUnix).big_integer())
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepoStorageCleanupJobs::UpdatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_repo_storage_cleanup_jobs_pending")
                .table(RepoStorageCleanupJobs::Table)
                .col(RepoStorageCleanupJobs::CompletedAtUnix)
                .col(RepoStorageCleanupJobs::NextRunAtUnix)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(SourceBlobCleanupJobs::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::ObjectKey)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::Generation)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::Sha256)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::GitOid)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::SizeBytes)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::LineCount)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::Attempts)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::NextRunAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(SourceBlobCleanupJobs::LastError).text())
                .col(ColumnDef::new(SourceBlobCleanupJobs::CompletedAtUnix).big_integer())
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SourceBlobCleanupJobs::UpdatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_source_blob_cleanup_jobs_pending")
                .table(SourceBlobCleanupJobs::Table)
                .col(SourceBlobCleanupJobs::CompletedAtUnix)
                .col(SourceBlobCleanupJobs::NextRunAtUnix)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    Ok(())
}
