use super::metadata_schema::*;
use sea_orm::DbErr;
use sea_orm_migration::{manager::SchemaManager, prelude::*};

pub async fn ensure_repository_fact_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(RepositorySettings::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepositorySettings::RepoId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(RepositorySettings::IncludeIgnoredFiles)
                        .boolean()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositorySettings::ReviewPushesBeforeApplying)
                        .boolean()
                        .not_null(),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_settings_repo")
                        .from(RepositorySettings::Table, RepositorySettings::RepoId)
                        .to(Repositories::Table, Repositories::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(RepositoryFirstPushTokens::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepositoryFirstPushTokens::RepoId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(RepositoryFirstPushTokens::TokenHash)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryFirstPushTokens::OwnerUserId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryFirstPushTokens::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryFirstPushTokens::ExpiresAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(RepositoryFirstPushTokens::UsedAtUnix).big_integer())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_first_push_tokens_repo")
                        .from(
                            RepositoryFirstPushTokens::Table,
                            RepositoryFirstPushTokens::RepoId,
                        )
                        .to(Repositories::Table, Repositories::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_first_push_tokens_owner")
                        .from(
                            RepositoryFirstPushTokens::Table,
                            RepositoryFirstPushTokens::OwnerUserId,
                        )
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(RepositoryGitPushTokens::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepositoryGitPushTokens::RepoId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(RepositoryGitPushTokens::TokenHash)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitPushTokens::OwnerUserId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitPushTokens::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_git_push_tokens_repo")
                        .from(
                            RepositoryGitPushTokens::Table,
                            RepositoryGitPushTokens::RepoId,
                        )
                        .to(Repositories::Table, Repositories::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_git_push_tokens_owner")
                        .from(
                            RepositoryGitPushTokens::Table,
                            RepositoryGitPushTokens::OwnerUserId,
                        )
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(RepositoryGitCloneTokens::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepositoryGitCloneTokens::RepoId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitCloneTokens::TokenHash)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitCloneTokens::UserId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitCloneTokens::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .primary_key(
                    Index::create()
                        .name("pk_scope_repository_git_clone_tokens")
                        .col(RepositoryGitCloneTokens::RepoId)
                        .col(RepositoryGitCloneTokens::TokenHash),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_git_clone_tokens_repo")
                        .from(
                            RepositoryGitCloneTokens::Table,
                            RepositoryGitCloneTokens::RepoId,
                        )
                        .to(Repositories::Table, Repositories::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_git_clone_tokens_user")
                        .from(
                            RepositoryGitCloneTokens::Table,
                            RepositoryGitCloneTokens::UserId,
                        )
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_repository_git_clone_tokens_user")
                .table(RepositoryGitCloneTokens::Table)
                .col(RepositoryGitCloneTokens::UserId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(RepositoryGitSnapshots::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::RepoId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::ObjectKey)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::Sha256)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::GitOid)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::SizeBytes)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(RepositoryGitSnapshots::LineCount)
                        .big_integer()
                        .not_null(),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_repository_git_snapshots_repo")
                        .from(
                            RepositoryGitSnapshots::Table,
                            RepositoryGitSnapshots::RepoId,
                        )
                        .to(Repositories::Table, Repositories::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    Ok(())
}
