use super::metadata_schema::*;
use sea_orm::DbErr;
use sea_orm_migration::{manager::SchemaManager, prelude::*};

pub async fn ensure_auth_tables(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Users::Table)
                .if_not_exists()
                .col(ColumnDef::new(Users::Id).string().not_null().primary_key())
                .col(
                    ColumnDef::new(Users::Handle)
                        .string()
                        .not_null()
                        .unique_key(),
                )
                .col(ColumnDef::new(Users::Email).string().not_null())
                .col(ColumnDef::new(Users::EmailVerified).boolean().not_null())
                .col(ColumnDef::new(Users::Access).string().not_null())
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_users_email")
                .table(Users::Table)
                .col(Users::Email)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(AuthIdentities::Table)
                .if_not_exists()
                .col(ColumnDef::new(AuthIdentities::Provider).string().not_null())
                .col(ColumnDef::new(AuthIdentities::Subject).string().not_null())
                .col(ColumnDef::new(AuthIdentities::UserId).string().not_null())
                .primary_key(
                    Index::create()
                        .name("pk_scope_auth_identities")
                        .col(AuthIdentities::Provider)
                        .col(AuthIdentities::Subject),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_auth_identities_user")
                        .from(AuthIdentities::Table, AuthIdentities::UserId)
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_auth_identities_user")
                .table(AuthIdentities::Table)
                .col(AuthIdentities::UserId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(CliDeviceLogins::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(CliDeviceLogins::DeviceCodeHash)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(CliDeviceLogins::UserCodeHash)
                        .string()
                        .not_null()
                        .unique_key(),
                )
                .col(
                    ColumnDef::new(CliDeviceLogins::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(CliDeviceLogins::ExpiresAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(CliDeviceLogins::CompletedUserId).string())
                .col(ColumnDef::new(CliDeviceLogins::CompletedAtUnix).big_integer())
                .col(ColumnDef::new(CliDeviceLogins::ConsumedAtUnix).big_integer())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_cli_device_logins_completed_user")
                        .from(CliDeviceLogins::Table, CliDeviceLogins::CompletedUserId)
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(CliBrowserLogins::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(CliBrowserLogins::RequestId)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(CliBrowserLogins::RequestSecretHash)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(CliBrowserLogins::CallbackUrl)
                        .text()
                        .not_null(),
                )
                .col(ColumnDef::new(CliBrowserLogins::CallbackCodeHash).string())
                .col(
                    ColumnDef::new(CliBrowserLogins::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(CliBrowserLogins::ExpiresAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(CliBrowserLogins::CompletedUserId).string())
                .col(ColumnDef::new(CliBrowserLogins::CompletedAtUnix).big_integer())
                .col(ColumnDef::new(CliBrowserLogins::ConsumedAtUnix).big_integer())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_cli_browser_logins_completed_user")
                        .from(CliBrowserLogins::Table, CliBrowserLogins::CompletedUserId)
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(CliExchangeGrants::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(CliExchangeGrants::GrantHash)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(CliExchangeGrants::UserId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(CliExchangeGrants::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(CliExchangeGrants::ExpiresAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(CliExchangeGrants::ConsumedAtUnix).big_integer())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_cli_exchange_grants_user")
                        .from(CliExchangeGrants::Table, CliExchangeGrants::UserId)
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_cli_exchange_grants_user")
                .table(CliExchangeGrants::Table)
                .col(CliExchangeGrants::UserId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_table(
            Table::create()
                .table(CliSessions::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(CliSessions::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(CliSessions::TokenHash)
                        .string()
                        .not_null()
                        .unique_key(),
                )
                .col(ColumnDef::new(CliSessions::UserId).string().not_null())
                .col(ColumnDef::new(CliSessions::Label).string().not_null())
                .col(
                    ColumnDef::new(CliSessions::CreatedAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(CliSessions::LastUsedAtUnix).big_integer())
                .col(
                    ColumnDef::new(CliSessions::ExpiresAtUnix)
                        .big_integer()
                        .not_null(),
                )
                .col(ColumnDef::new(CliSessions::RevokedAtUnix).big_integer())
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_scope_cli_sessions_user")
                        .from(CliSessions::Table, CliSessions::UserId)
                        .to(Users::Table, Users::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_scope_cli_sessions_user")
                .table(CliSessions::Table)
                .col(CliSessions::UserId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    Ok(())
}
