/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos.$owner.$repo'
import { Route as ReposOwnerRepoSettingsRouteImport } from './routes/repos.$owner.$repo.settings'
import { Route as ReposOwnerRepoReviewRouteImport } from './routes/repos.$owner.$repo.review'
import { Route as ReposOwnerRepoHistoryRouteImport } from './routes/repos.$owner.$repo.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/repos/$owner/$repo',
  path: '/repos/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoSettingsRoute = ReposOwnerRepoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)
const ReposOwnerRepoReviewRoute = ReposOwnerRepoReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)
const ReposOwnerRepoHistoryRoute = ReposOwnerRepoHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/history': typeof ReposOwnerRepoHistoryRoute
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/settings': typeof ReposOwnerRepoSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/history': typeof ReposOwnerRepoHistoryRoute
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/settings': typeof ReposOwnerRepoSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/history': typeof ReposOwnerRepoHistoryRoute
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/settings': typeof ReposOwnerRepoSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/history'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/history'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/settings'
  id:
    | '__root__'
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/history'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo/settings': {
      id: '/repos/$owner/$repo/settings'
      path: '/settings'
      fullPath: '/repos/$owner/$repo/settings'
      preLoaderRoute: typeof ReposOwnerRepoSettingsRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
    '/repos/$owner/$repo/review': {
      id: '/repos/$owner/$repo/review'
      path: '/review'
      fullPath: '/repos/$owner/$repo/review'
      preLoaderRoute: typeof ReposOwnerRepoReviewRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
    '/repos/$owner/$repo/history': {
      id: '/repos/$owner/$repo/history'
      path: '/history'
      fullPath: '/repos/$owner/$repo/history'
      preLoaderRoute: typeof ReposOwnerRepoHistoryRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
  }
}

interface ReposOwnerRepoRouteChildren {
  ReposOwnerRepoHistoryRoute: typeof ReposOwnerRepoHistoryRoute
  ReposOwnerRepoReviewRoute: typeof ReposOwnerRepoReviewRoute
  ReposOwnerRepoSettingsRoute: typeof ReposOwnerRepoSettingsRoute
}

const ReposOwnerRepoRouteChildren: ReposOwnerRepoRouteChildren = {
  ReposOwnerRepoHistoryRoute: ReposOwnerRepoHistoryRoute,
  ReposOwnerRepoReviewRoute: ReposOwnerRepoReviewRoute,
  ReposOwnerRepoSettingsRoute: ReposOwnerRepoSettingsRoute,
}

const ReposOwnerRepoRouteWithChildren = ReposOwnerRepoRoute._addFileChildren(
  ReposOwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
