/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSessionRouteImport } from './routes/auth.session'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ReposOwnerRepoRouteImport } from './routes/repos.$owner.$repo'
import { Route as ReposOwnerRepoSetupRouteImport } from './routes/repos.$owner.$repo.setup'
import { Route as ReposOwnerRepoReviewRouteImport } from './routes/repos.$owner.$repo.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionRoute = AuthSessionRouteImport.update({
  id: '/auth/session',
  path: '/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoRoute = ReposOwnerRepoRouteImport.update({
  id: '/repos/$owner/$repo',
  path: '/repos/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ReposOwnerRepoSetupRoute = ReposOwnerRepoSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)
const ReposOwnerRepoReviewRoute = ReposOwnerRepoReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ReposOwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/session': typeof AuthSessionRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/setup': typeof ReposOwnerRepoSetupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/session': typeof AuthSessionRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/setup': typeof ReposOwnerRepoSetupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/session': typeof AuthSessionRoute
  '/repos/$owner/$repo': typeof ReposOwnerRepoRouteWithChildren
  '/repos/$owner/$repo/review': typeof ReposOwnerRepoReviewRoute
  '/repos/$owner/$repo/setup': typeof ReposOwnerRepoSetupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/callback'
    | '/auth/session'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/setup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/session'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/setup'
  id:
    | '__root__'
    | '/'
    | '/auth/callback'
    | '/auth/session'
    | '/repos/$owner/$repo'
    | '/repos/$owner/$repo/review'
    | '/repos/$owner/$repo/setup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSessionRoute: typeof AuthSessionRoute
  ReposOwnerRepoRoute: typeof ReposOwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/session': {
      id: '/auth/session'
      path: '/auth/session'
      fullPath: '/auth/session'
      preLoaderRoute: typeof AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo': {
      id: '/repos/$owner/$repo'
      path: '/repos/$owner/$repo'
      fullPath: '/repos/$owner/$repo'
      preLoaderRoute: typeof ReposOwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repos/$owner/$repo/setup': {
      id: '/repos/$owner/$repo/setup'
      path: '/setup'
      fullPath: '/repos/$owner/$repo/setup'
      preLoaderRoute: typeof ReposOwnerRepoSetupRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
    '/repos/$owner/$repo/review': {
      id: '/repos/$owner/$repo/review'
      path: '/review'
      fullPath: '/repos/$owner/$repo/review'
      preLoaderRoute: typeof ReposOwnerRepoReviewRouteImport
      parentRoute: typeof ReposOwnerRepoRoute
    }
  }
}

interface ReposOwnerRepoRouteChildren {
  ReposOwnerRepoReviewRoute: typeof ReposOwnerRepoReviewRoute
  ReposOwnerRepoSetupRoute: typeof ReposOwnerRepoSetupRoute
}

const ReposOwnerRepoRouteChildren: ReposOwnerRepoRouteChildren = {
  ReposOwnerRepoReviewRoute: ReposOwnerRepoReviewRoute,
  ReposOwnerRepoSetupRoute: ReposOwnerRepoSetupRoute,
}

const ReposOwnerRepoRouteWithChildren = ReposOwnerRepoRoute._addFileChildren(
  ReposOwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSessionRoute: AuthSessionRoute,
  ReposOwnerRepoRoute: ReposOwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
