use crate::domain::{
    policy::Visibility,
    store::{FirstPushTokenStatus, RepoPublicationState, RepoRole, StagedFileChangeKind},
};
use crate::http::responses::*;
use std::{fs, path::PathBuf};
use ts_rs::TS;

#[test]
#[ignore = "exports TypeScript API types for the web contract check"]
fn export_api_types() {
    let ts_config = ts_rs::Config::new().with_large_int("number");
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output_path = std::env::var_os("SCOPE_API_TS_EXPORT_PATH")
        .map(PathBuf::from)
        .unwrap_or_else(|| manifest_dir.join("../web/src/api/types.generated.ts"));
    let declarations = [
        generated_header(),
        declaration::<Visibility>(&ts_config),
        declaration::<RepoRole>(&ts_config),
        declaration::<RepoPublicationState>(&ts_config),
        declaration::<FirstPushTokenStatus>(&ts_config),
        declaration::<StagedFileChangeKind>(&ts_config),
        declaration::<ProjectionPreviewAudience>(&ts_config),
        declaration::<ProjectionPreviewSource>(&ts_config),
        declaration::<AccountSessionResponse>(&ts_config),
        declaration::<UserResponse>(&ts_config),
        declaration::<SessionResponse>(&ts_config),
        declaration::<SessionIdentity>(&ts_config),
        declaration::<SessionRepo>(&ts_config),
        declaration::<SessionCapabilities>(&ts_config),
        declaration::<RepoSummaryResponse>(&ts_config),
        declaration::<CreateRepoRequest>(&ts_config),
        declaration::<CreateRepoResponse>(&ts_config),
        declaration::<DeleteRepoResponse>(&ts_config),
        declaration::<RepoSetupResponse>(&ts_config),
        declaration::<RepoGitCredentialResponse>(&ts_config),
        declaration::<FirstPushTokenResponse>(&ts_config),
        declaration::<GitPushTokenResponse>(&ts_config),
        declaration::<RepoFileResponse>(&ts_config),
        declaration::<RepoSettingsResponse>(&ts_config),
        declaration::<UpdateRepoSettingsRequest>(&ts_config),
        declaration::<UpdateFileVisibilityRequest>(&ts_config),
        declaration::<UpdateStagedFileVisibilityRequest>(&ts_config),
        declaration::<ReviewFileDiffRequest>(&ts_config),
        declaration::<CommitHistoryRequest>(&ts_config),
        declaration::<CommitFileDiffRequest>(&ts_config),
        declaration::<ReviewFileDiffResponse>(&ts_config),
        declaration::<ReviewLineDiffResponse>(&ts_config),
        declaration::<PendingImportReviewResponse>(&ts_config),
        declaration::<StagedUpdateResponse>(&ts_config),
        declaration::<StagedFileResponse>(&ts_config),
        declaration::<CommitHistoryResponse>(&ts_config),
        declaration::<CommitSummaryResponse>(&ts_config),
        declaration::<CommitDetailResponse>(&ts_config),
        declaration::<CommitFileResponse>(&ts_config),
        declaration::<ProjectionPreviewRequest>(&ts_config),
        declaration::<ProjectionPreviewResponse>(&ts_config),
        declaration::<ProjectionPreviewFileResponse>(&ts_config),
        declaration::<ProjectionPreviewCommitResponse>(&ts_config),
        declaration::<ProjectionPreviewCommitVisibilityResponse>(&ts_config),
        declaration::<ProjectionPreviewSummaryResponse>(&ts_config),
    ]
    .join("\n\n");

    fs::write(output_path, format!("{declarations}\n")).expect("write generated API types");
}

fn declaration<T: TS>(config: &ts_rs::Config) -> String {
    format!("export {}", T::decl(config))
}

fn generated_header() -> String {
    [
        "// This file is generated from Rust API response/request types.",
        "// Run `cargo test --manifest-path api/Cargo.toml export_api_types -- --ignored` to update it.",
        "// Do not edit this file by hand.",
    ]
    .join("\n")
}
