minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - konsistent
  - '@konsistent/convention'
trustPolicy: no-downgrade
blockExoticSubdeps: true
supportedArchitectures:
  os:
    - current
    - linux
    - win32
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
allowBuilds:
  bufferutil: false
  core-js: false
  utf-8-validate: false
